# Generated by Django 3.2.4 on 2021-06-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneleftfootapi', '0002_danceuser_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danceuser',
            name='img',
        ),
    ]
