# Generated by Django 3.2.4 on 2021-06-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneleftfootapi', '0003_remove_danceuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceuser',
            name='img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
